### ISSUE TITLE
invert the color between opened file tabs and active tab : light color = active tab

### ISSUE THREAD

**Issue by perph001** [zigagrcar/vscode-monokai-phoenix#1]
Hi,

Would it be possible to invert the color between opened file tabs and active tab (or give the option) ?

The lighter color for the active file tab is more intuitive ... in fact I mix them up frequently enough to take the time write this comment ;)

Thanks in advance,
Phil

**Comment by zigagrcar** [comment]
Yes, if I understand correctly you want to change tab color, if so you can customize it in your user settings like this and just change the color code to the one you want

`    "workbench.colorCustomizations": {
        "tab.activeBackground": "#0000ff",
        "tab.inactiveBackground": "#ffffff"
      }`

source: https://code.visualstudio.com/api/references/theme-color
